ldlidar_node:
  ros__parameters:
    product_name: LDLiDAR_LD06
    topic_name: scan
    frame_id: ldlidar_link
    port_name: /dev/rplidar
    port_baudrate: 230400
    laser_scan_dir: True
    enable_angle_crop_func: False
    angle_crop_min: 135.0
    angle_crop_max: 225.0

